- name: instala pacote
  ansible.builtin.apt:
    name: bzip2
  become: true

- name: instala pacote paralelo
  ansible.builtin.apt:
    name: lbzip2
  become: true
  when: system_archive_parallel is defined and system_archive_parallel
