- name: instala pacote
  ansible.builtin.apt:
    name: htop
  become: true

- name: verifica configuração
  ansible.builtin.stat:
    path: '{{ user_config_dir }}/htop'
  register: config
  when: user_config_dir is defined

- name: cria diretório de configuração
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/htop'
    state: directory
    mode: 0755
  when: user_config_dir is defined and config.stat.exists

- name: configura htoprc
  ansible.builtin.file:
    src: '{{ user_config_dir }}/htop/htoprc'
    path: '{{ ansible_user_dir }}/.config/htop/htoprc'
    state: link
    force: true
  when: user_config_dir is defined and config.stat.exists
