- name: define diretório
  ansible.builtin.set_fact:
    user_icons_dir: '{{ ansible_user_dir }}/.local/share/icons'

- name: cria diretório
  ansible.builtin.file:
    path: '{{ user_icons_dir }}'
    state: directory
    mode: 0755
