- name: adiciona chave do repositório
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  become: true

- name: adiciona repositório
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: terraform
  become: true

- name: instala pacote
  ansible.builtin.apt:
    name: terraform
  become: true
