- name: instala pacote
  ansible.builtin.apt:
    name:
      - xfce4
      - desktop-base
      - gnome-icon-theme
      - policykit-1-gnome
      - xfce4-notifyd
      - xfce4-screenshooter
      - xfce4-terminal
  become: true

- name: instala pacotes extras
  ansible.builtin.apt:
    name:
      - xfce4-weather-plugin
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - tumbler
      - tumbler-plugins-extra
  become: true
  when: xfce4_extras

- name: instala pacotes extras para notebook
  ansible.builtin.apt:
    name:
      - xfce4-battery-plugin
      - xfce4-power-manager
      - xfce4-power-manager-plugins
  become: true
  when: xfce4_extras and system_notebook is defined and system_notebook

- name: instala utilitários
  ansible.builtin.apt:
    name: libnotify-bin
  become: true
  when: xfce4_utils
