- name: instala pacote
  ansible.builtin.apt:
    name: mpv
  become: true

- name: verifica configuração
  ansible.builtin.stat:
    path: '{{ user_config_dir }}/mpv'
  register: config
  when: user_config_dir is defined

- name: cria diretório de configuração
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/mpv'
    state: directory
    mode: 0755
  when: user_config_dir is defined and config.stat.exists

- name: configura mpv.conf
  ansible.builtin.file:
    src: '{{ user_config_dir }}/mpv/mpv.conf'
    path: '{{ ansible_user_dir }}/.config/mpv/mpv.conf'
    state: link
    force: true
  when: user_config_dir is defined and config.stat.exists

- name: configura scripts
  ansible.builtin.file:
    src: '{{ user_config_dir }}/mpv/scripts'
    path: '{{ ansible_user_dir }}/.config/mpv/scripts'
    state: link
    force: true
  when: user_config_dir is defined and config.stat.exists
