- name: cria diretório
  ansible.builtin.file:
    path: /opt/firefox-dev
    state: directory
    mode: 0755

- name: baixa programa
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang={{ firefox_dev_lang }}
    dest: /opt/firefox-dev
    extra_opts:
      - --strip-components=1
    creates: /opt/firefox-dev/firefox

- name: copia arquivo .desktop
  ansible.builtin.template:
    src: firefox-dev.desktop.j2
    dest: '{{ user_applications_dir }}/firefox-dev.desktop'
    mode: 0755

- name: adiciona nas alternativas
  community.general.alternatives:
    link: /usr/bin/x-www-browser
    name: x-www-browser
    path: /opt/firefox-dev/firefox
    priority: 99
  become: true
