- name: verifica diretório de dados
  ansible.builtin.stat:
    path: '{{ user_data_dir }}/templates'
  register: config
  when: user_data_dir is defined

- name: cria arquivo user-dirs.dirs
  ansible.builtin.command:
    cmd: xdg-user-dirs-update
    creates: '{{ ansible_user_dir }}/.config/user-dirs.dirs'
  when: user_data_dir is defined and config.stat.exists

- name: configura xdg
  ansible.builtin.replace:
    path: '{{ ansible_user_dir }}/.config/user-dirs.dirs'
    regexp: ^XDG_TEMPLATES_DIR=.*
    replace: XDG_TEMPLATES_DIR="{{ user_data_dir }}/templates"
  when: user_data_dir is defined and config.stat.exists
