name: Lint

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup do python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instala lint
        run: pip install 'ansible>=2.10,<3' 'ansible-lint>=5.2,<6'

      - name: Executa lint
        run: ansible-lint
